### ISSUE TITLE
ORUN issue

### ISSUE THREAD

**Issue by prats2018** [NXP/i3c-slave-design#11]
Hi,
I am observing tb_orun during read . The description says The internal from-bus buffer/FIFO was overrun (too many chars coming in and not drained by the app fast enough).
How to resolve this.

Thanks
Prathusha

**Comment by pkimelman-nxp** [comment]
To bus overrun means you are writing to the TX FIFO too fast. The software should be using the TX status or interrupt. If polling, then read the STATUS register and check of TX has space. If using the interrupt you can fill it the same way. The datactrl register will also tell you how much space.
Note that you can configure the TX FIFO size to be whatever you want.

Sent from my iPhone

On Jul 18, 2019, at 9:33 PM, prats2018 <notifications@github.com<mailto:notifications@github.com>> wrote:


Caution: EXT Email

Hi,
I am observing tb_orun during read . The description says The internal from-bus buffer/FIFO was overrun (too many chars coming in and not drained by the app fast enough).
How to resolve this.

Thanks
Prathusha

**Comment by prats2018** [comment]
Thanks, we have increased the Internal FIFO Threshold to 4.So overrun error is resolved.
But, now there is another issue, while reading , we are getting underrun issue..:(
Did we miss any settings? Can you check this waveform attached here?
Note: We are not configuring any APB registers. sdr_Slv_ok  bit is tied to 1. 
![i2c_slave](https://user-images.githubusercontent.com/41048446/61523839-c2839200-aa32-11e9-876c-61eb59d23590.png)

**Comment by pkimelman-nxp** [comment]
The underrun simply means it ran out of data, but was not told last one was the last (end). You need to write END if it is the end of the data you want to send. You can either use WDATAB with the END bit, or use WDATABE for this. If using half-words, then WDATAH and WDATAHE.


On Jul 19, 2019, at 2:07 AM, prats2018 <notifications@github.com<mailto:notifications@github.com>> wrote:


Caution: EXT Email

Thanks, we have increased the Internal FIFO Threshold to 4.So overrun error is resolved.
But, now there is another issue, while reading , we are getting underrun issue..:(
Did we miss any settings? Can you check this waveform attached here?
Note: We are not configuring any APB registers. sdr_Slv_ok bit is tied to 1.
[i2c_slave]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F41048446%2F61523839-c2839200-aa32-11e9-876c-61eb59d23590.png&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C205d03f774a84d78978608d70c28977d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636991240794113962&sdata=%2BCuvSRws5obssaK3rdRyrLaaHIa0vW5fMZ1MPHOAU8k%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNXP%2Fi3c-slave-design%2Fissues%2F11%3Femail_source%3Dnotifications%26email_token%3DAFNELXZFK3UZF7DCV4J2UGDQAF76XA5CNFSM4IFCHMKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2LCAIQ%23issuecomment-513155106&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C205d03f774a84d78978608d70c28977d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636991240794113962&sdata=CSxu6OK4XCj%2BFLjiAHbUv6OYeUxveyar%2FlL%2Ff8cnEO4%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNELXYOADUU6FSIOKCDWL3QAF76XANCNFSM4IFCHMKA&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C205d03f774a84d78978608d70c28977d%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636991240794113962&sdata=p5kh12%2Fd3c4dbBA1YlQABdbbnaI7xv6uZGAarumdtr8%3D&reserved=0>.

--
Paul Kimelman – Automotive Platform Architecture
408.906.9676
