### ISSUE TITLE
With public release of I3C spec, is the NDA still needed

### ISSUE THREAD

**Issue by BurtHarris** [NXP/i3c-slave-design#5]
Not a big deal, I'm just glad the spec has been made public.

**Comment by BurtHarris** [comment]
Hello @pkimelman-nxp, 

It may take a lawyer rather than engineer to figure this out, but what I've been expecting one of several licenses as described under at https://en.wikipedia.org/wiki/BSD_licenses.

The [NXP website documentation](https://www.nxp.com/products/product-information/ip-block-licensing/mipi-i3c:MIPI) indicates that the **Free Basic Slave** IP is under BSD license, but license here is far from a typical BSD agreement.      

Perhaps this indicates the documentation here is out-of-date with NXP's actual licensing policy, or perhaps it's that I've misunderstood the reference to BSD license made on the NXP site.

**Comment by pkimelman-nxp** [comment]
MIPI forces NXP to add a “copyright” license on the specification, which creates some restrictions. We need to see if the “open" publication of the I3C spec has a less restrictive license. If so, we will use that. This was not our choice. The current license allows you to use the RTL freely, but limits distribution due to the MIPI constraints. Obviously we preserve the copyright as with Apache/BSD. We did originally have a pure Apache license with typical no-warranty and so on.
When I3C Basic is released, we will then see if we can move back to an Apache license. That should happen in mid to late October.

Regards, Paul



On Aug 25, 2018, at 9:32 AM, Burt Harris <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @pkimelman-nxp<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpkimelman-nxp&data=02%7C01%7Cpaul.kimelman%40nxp.com%7Ce7ffc9009aa54a08d88608d60aa8656e%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636708115706006520&sdata=GffIw9klzEeectU2SKOOiVS4Q9aWKYHJXoqK5k0Q3gE%3D&reserved=0>,

It may take a lawyer rather than engineer to figure this out, but what I've been expecting one of several licenses as described under at https://en.wikipedia.org/wiki/BSD_licenses<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBSD_licenses&data=02%7C01%7Cpaul.kimelman%40nxp.com%7Ce7ffc9009aa54a08d88608d60aa8656e%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636708115706006520&sdata=scGhyzllyu5BOIolGntYLJnBqK3%2BS%2Bh7rxOfrEd5Yl4%3D&reserved=0>.

The NXP website documentation<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nxp.com%2Fproducts%2Fproduct-information%2Fip-block-licensing%2Fmipi-i3c%3AMIPI&data=02%7C01%7Cpaul.kimelman%40nxp.com%7Ce7ffc9009aa54a08d88608d60aa8656e%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636708115706016516&sdata=v4TrbuX9nPP9OjlFVE9Lqvm4ChpZtIoS39S%2B7xO%2FduI%3D&reserved=0> indicates that the Free Basic Slave IP is under BSD license, but license here is far from a typical BSD agreement.

Perhaps this indicates the documentation here is out-of-date with NXP's actual licensing policy, or perhaps it's that I've misunderstood the reference to BSD license made on the NXP site.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNXP%2Fi3c-slave-design%2Fissues%2F5%23issuecomment-415980988&data=02%7C01%7Cpaul.kimelman%40nxp.com%7Ce7ffc9009aa54a08d88608d60aa8656e%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636708115706016516&sdata=ykC70Ffs9Mn8JJc%2FtdFbjt8u8fEIS0TXZlcVH3rJAws%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVpF36Q1Nba6WrgvECj4e8aHU4V7hOq6ks5uUXwvgaJpZM4ST8eS&data=02%7C01%7Cpaul.kimelman%40nxp.com%7Ce7ffc9009aa54a08d88608d60aa8656e%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636708115706026525&sdata=xiO96ab%2FmF9w0ml3fnuIGlldlA%2Ft3pdKgAvJ%2F%2BBz%2FEg%3D&reserved=0>.

--
Paul Kimelman – Automotive Platform Architecture
408.906.9676

**Comment by pkimelman-nxp** [comment]
The Slave has now been republished with BSD License to go with the release of I3C Basic v1.0. This new publication allow non-members to not only read the spec but build HW from it. So, the RTL is released as BSD again.

**Comment by pkimelman-nxp** [comment]
Since the above comment clarified that we now have a normal BSD license, this is closed.

**Comment by BurtHarris** [comment]
Thank you @pkimelman-nxp
