### ISSUE TITLE
Basic testbench

### ISSUE THREAD

**Issue by matticica** [NXP/i3c-slave-design#7]
Is there a very basic testbench to simulate the interface?

**Comment by pkimelman-nxp** [comment]
At the moment, no. That is available from various companies as well as with the licensed version. We will likely add a simple vector checkout of ENTDAA and some messages. This would show up with the next update - planned for July.

Regards, Paul

On Jun 7, 2019, at 6:20 AM, matticica <notifications@github.com<mailto:notifications@github.com>> wrote:


Caution: EXT Email

Is there a very basic testbench to simulate the interface?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNXP%2Fi3c-slave-design%2Fissues%2F7%3Femail_source%3Dnotifications%26email_token%3DAFNELX7ZCL2WWZFXMPETDZTPZJOANA5CNFSM4HVXAJWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYIAUEA&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C7baee244636743f84d6e08d6eb4adc7c%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636955104091798262&sdata=R3y3rUj4xyND%2Fq4Km0eKDRlkkcqvQbFoR7gY6pEkcMU%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNELX3OTYLS6NPV7JI6TYLPZJOANANCNFSM4HVXAJWA&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C7baee244636743f84d6e08d6eb4adc7c%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636955104091798262&sdata=lhV045Oa8WGAjPYMHiKI5e3Foj9OtAF%2Bwcx3xDwg9GE%3D&reserved=0>.

--
Paul Kimelman – Automotive Platform Architecture
408.906.9676

**Comment by pkimelman-nxp** [comment]
The update likely will get moved into Aug. No specific errors to rush it out, and a few new features will show up in the upcoming release and those are being finalized.

**Comment by rosholm** [comment]
Can you reveal what the new features are?
Also, is there a roadmap/list of planned new features?

**Comment by pkimelman-nxp** [comment]
Yes, the update adds new optional features and the vector test bench.
The main new features are:
1. Slave Reset and SETAASA.
2. More i2c features if needed (e.g. extended address, device ID, SW reset).
3. Some bug fixes.

Plan is early Sept.

Does the update include any new features in the I3C slave or is it only new features in the testbench?

Also, is there a roadmap/list of planned new features?

--
Paul Kimelman – Automotive Platform Architecture
408.906.9676

**Comment by pkimelman-nxp** [comment]
The test bench vector set is not yet in the release update, but I will leave the other issue open about this subject. The new update (1.1.11) has features and fixes as noted.
