### ISSUE TITLE
I3c slave configured as i2c slave

### ISSUE THREAD

**Issue by prats2018** [NXP/i3c-slave-design#9]
Hi,
I m configuring this nxp slave as  i2c slave with i2c master, Read operation is not happening, I am able to see the data in fb_data, but read is not being initiated. Can you let me know the configuration required to be set for making it work as i2c.

Thanks
Prats

**Comment by pkimelman-nxp** [comment]
I am assuming you are using the APB Slave wrapper and not autonomous slave.
If you do not put data into the TX FIFO, it will NACK the read and it will set the ERRWARN bit to tell you that (underrun on address).
The normal model is that they write a single byte (index) and you get that in the RX FIFO. You then push data into the TX FIFO which  is what they read.
The fb_data value should have been pushed into the RX FIFO with fb_data_done. Your app should have seen it then.
Regards, Paul


On Jul 12, 2019, at 5:33 AM, prats2018 <notifications@github.com<mailto:notifications@github.com>> wrote:


Caution: EXT Email

Hi,
I m configuring this nxp slave as i2c slave with i2c master, Read operation is not happening, I am able to see the data in fb_data, but read is not being initiated. Can you let me know the configuration required to be set for making it work as i2c.

Thanks
Prats

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNXP%2Fi3c-slave-design%2Fissues%2F9%3Femail_source%3Dnotifications%26email_token%3DAFNELX4NOQ6FLCWDH3XCC4TP7B223A5CNFSM4ICI4DSKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G63Z2QQ&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C8004f281f1c94181853508d706c531cc%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636985316320168325&sdata=OPV%2F%2B91IVBlIhpi2jhp6KCb09QY4OXKVWDjbitXV%2BbU%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNELX5OK5FB4LTXZGTI6UDP7B223ANCNFSM4ICI4DSA&data=02%7C01%7Cpaul.kimelman%40nxp.com%7C8004f281f1c94181853508d706c531cc%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636985316320178311&sdata=6EdaRYKM49UjtTLVHP4jI7Zk9jkFnJ4Jjohso9zZ%2B94%3D&reserved=0>.

--
Paul Kimelman – Automotive Platform Architecture
408.906.9676

**Comment by pkimelman-nxp** [comment]
prats2018, please let me know if this answered the issue or you are still having problems.
